title: Frani Walks Dogs
description: San Francisco Dog Walker
sitename: Frani Walker
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME

  plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-125481387-1        # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

  #Matomo:                   # Add, if you want to track with Matomo (former Piwik Analytics)
  #  url: matomo.example.com # Required - url to Matomo installation without trailing /
  #  siteId: "1234"          # Required - replace with your Matomo site id (Write id as string)

#  Piwik:                    # Add, if you want to track with Piwik
  #  url: piwik.example.com  # Required - url to Piwik installation without trailing /
  #  siteId: "1234"          # Required - replace with your Piwik site id (Write id as string)

  #MPulse:                   # Add if you want to track performance with mPulse
    #apikey: XXXXX-YYYYY-ZZZZZ-AAAAA-23456   # Required - replace with your mPulse API key
