title: Frani Walks Dogs
description: San Francisco Dog Walker
sitename: Frani Walker
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
